config/custom-environment-variables.yaml
config/default.yaml
config/rabbitmq.js
package.json
plugins/worker/lib/jobs.js
test/plugins/worker/lib/filter.test.js
test/plugins/worker/lib/jobs.test.js

At times the connection to rabbitmq server is lost.
This PR upgrades amqp-connection-manager package version from v2.3.0 [Nov 20, 2018] to v3.2.0 [Jan, 20, 2020] and enable rabbitmq heartbeat check and reconnect interval via connect options config instead.
[screwdriver-cd/screwdriver#2052](https://github.com/screwdriver-cd/screwdriver/issues/2052)

feat(2052): Upgrade amqp package, add rabbitmq connect options and remove unused exchange type var

---

plugins/helper.js
plugins/queue/scheduler.js

In case of frozen builds update build was called 2 times once for status and once for stats which resulted in 403 on second update.
This PR merges the build update for stats and status in case of frozen builds and fixes the 403 issue

fix: Prevent multiple build update in case of frozen jobs

---

lib/queue.js
lib/registerPlugins.js
lib/server.js
package.json
plugins/helper.js
plugins/logging.js
plugins/queue/scheduler.js
plugins/status.js
plugins/worker/lib/timeout.js
plugins/worker/worker.js
test/lib/registerPlugins.test.js
test/plugins/helper.test.js
test/plugins/worker/lib/timeout.test.js
test/plugins/worker/worker.test.js

When multiple node-resque workers start polling it results in unnecessary chatty calls to Redis every 5 seconds which is not optimized. With no lock checks this results the same buildId be processed several times based on the no of active workers. Also multiple polling by workers every  5seconds is not very desirable for timeout use case.
This PR fixes the above issues:
1. Adds a lock of 1sec on the key buildId in redis and unlocks it after processing. At the same instant if any other worker tries to acquire lock it fails and goes to the next item
2. Since we cannot modify the node-resque polling time, it adds a backoff strategy to the polling by workers and reduces polling interval  to every 60 seconds.
https://github.com/mike-marcacci/node-redlock/blob/master/README.md#usage-promise-styl …

feat: Implement lock check in processing build timeouts

---

lib/queue.js
lib/registerPlugins.js
plugins/auth/index.js
plugins/queue/delete.js
plugins/queue/put.js
plugins/queue/scheduler.js
plugins/worker/create.js
plugins/worker/lib/CacheFilter.js
plugins/worker/lib/jobs.js
plugins/worker/lib/timeout.js
plugins/worker/worker.js
test/data/fullConfig.json
test/lib/queue.test.js
test/plugins/queue/index.test.js
test/plugins/queue/scheduler.test.js
test/plugins/queue/stats.test.js
test/plugins/worker/create.test.js
test/plugins/worker/lib/cacheFilter.test.js
test/plugins/worker/lib/jobs.test.js
test/plugins/worker/worker.test.js

Cache cleanup buttons in Pipeline settings page, does not clear the cache when using disk cache.
This PR implements a cache clear mechanism for disk based strategy by sending a message to the rabbitmq consumer
https://github.com/screwdriver-cd/screwdriver/issues/2087
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

feat(2087): Cache Clear feature implementation

---

plugins/queue/scheduler.js
plugins/worker/lib/BlockedBy.js
plugins/worker/lib/jobs.js
plugins/worker/worker.js
test/plugins/queue/scheduler.test.js
test/plugins/worker/worker.test.js

JWT token generation had a default expiry time of 1 hr, many builds may run for several hours being blocked so we need to increase the expiry
This PR increases the temporal token expiry to 12hrs

fix: Increase jwt temporal token expiry to 12hrs

---

config/custom-environment-variables.yaml
config/default.yaml

We want to use kata in the environment without using buildcluster-queue-worker.
- Add `executor.k8s.options.kubernetes.privileged` to config files
- Add `executor.k8s.options.kubernetes.runtimeClass` to config files
- Add `executor.k8s-vm.options.kubernetes.privileged` to config files
https://github.com/screwdriver-cd/screwdriver/issues/818
https://github.com/screwdriver-cd/buildcluster-queue-worker/pull/48
https://github.com/screwdriver-cd/buildcluster-queue-worker/pull/53

fix: use runtimeClass without buildcluster-queue-worker

---

config/custom-environment-variables.yaml
config/rabbitmq.js

Kubernetes can not set boolean values as environment variables. 
So, we can not switch on/off by using `SCHEDULER_ENABLED` environment variable.
Convert `SCHEDULER_ENABLED` value from string to boolean.
Related Issue:
https://github.com/screwdriver-cd/screwdriver/issues/2240

fix(2240): Convert SCHEDULER_ENABLED value from string to boolean.

---

plugins/helper.js
plugins/worker/lib/BlockedBy.js
plugins/worker/lib/timeout.js
test/plugins/helper.test.js
test/plugins/queue/index.test.js
test/plugins/queue/scheduler.test.js
test/plugins/queue/stats.test.js
test/plugins/queue/utils/cron.test.js
test/plugins/queue/utils/freezeWindows.test.js
test/plugins/worker/create.test.js
test/plugins/worker/lib/BlockedBy.test.js
test/plugins/worker/lib/cacheFilter.test.js
test/plugins/worker/lib/filter.test.js
test/plugins/worker/lib/timeout.test.js
test/plugins/worker/worker.test.js

When queue-service tries to update the build state and receives an err from the API, queue-service should not be restarted.
However, currently, the queue-service will be restarted with unhandledRejection when receives an err from the API.
Add error handling method when updating buildStatus.
screwdriver-cd/screwdriver#2503

fix(2503): Properly handling when failing update build status

---

plugins/queue/scheduler.js
test/plugins/queue/scheduler.test.js

We should send QUEUED status when start build so that QUEUED notifications only sent once.
Queue-service updates build with `status: 'QUEUED'` when start build.
issues: screwdriver-cd/screwdriver#2096
API fix: https://github.com/screwdriver-cd/screwdriver/pull/2512

[2] fix(2096): Pass QUEUED status when start builds

---

lib/queue.js
plugins/helper.js
test/plugins/helper.test.js

Retry is not working as expected.
This PR:
- renames from `retryOptions` => `retry`
- throws error in retry strategy in `afterResponse` hook to correctly trigger retries
Related to https://github.com/screwdriver-cd/queue-service/pull/33

fix(1961): Retry with new request package

---

package.json

Pulling in latest executor-k8s with retry changes.
Related to https://github.com/screwdriver-cd/executor-k8s/pull/173

fix: Pull in latest executor-k8s with new retry

---

lib/queue.js
plugins/queue/put.js
plugins/queue/scheduler.js
test/lib/queue.test.js
test/plugins/queue/index.test.js
test/plugins/queue/scheduler.test.js

Implement `/v1/queue/message?type=unzip` endpoint for SD_ZIP_ARTIFACTS in order to make queue-service available to that function.
- Create unzip queue for SD_ZIP_ARTIFACTS job
- Implements `scheduler.unzipArtifacts()`
https://github.com/screwdriver-cd/screwdriver/issues/1500
https://github.com/screwdriver-cd/screwdriver/pull/2583

fix(1500): Make queue-service available for SD_ZIP_ARTIFACTS

---

config/custom-environment-variables.yaml
config/default.yaml
package.json
plugins/queue/scheduler.js
plugins/worker/lib/jobs.js
test/data/executorConfig.json
test/plugins/worker/lib/jobs.test.js

To enable Screwdriver AWS Integration we need to integrate the [aws-producer-service](https://github.com/screwdriver-cd/aws-producer-service) with the existing queuing service
This PR adds `aws-producer-service` as a dependency and relays messages to the service for AWS executors
https://github.com/screwdriver-cd/screwdriver/issues/2559
https://github.com/screwdriver-cd/screwdriver/issues/2550

feat(#2559): integrate producer-svc with queuesvc

---

lib/queue.js
plugins/queue/put.js
plugins/queue/scheduler.js
test/lib/queue.test.js
test/plugins/queue/index.test.js
test/plugins/queue/scheduler.test.js

We are going to change the way we handle webhooks, and when the API receives a webhook, it will create a Queue Service event. Therefore, Queue Service needs to respond to the webhook-related requests from the API.
We implement `/queue/message?type=webhook` endpoint for webhook-related requests. Webhook configs sent here will be stored in redis. 
https://github.com/screwdriver-cd/screwdriver/issues/1769#issuecomment-934107626

feat(1769): Add function to respond to request about webhook

---

plugins/helper.js
plugins/worker/lib/jobs.js
plugins/worker/worker.js
test/plugins/helper.test.js
test/plugins/worker/lib/jobs.test.js
test/plugins/worker/worker.test.js

We modified it [last time](https://github.com/screwdriver-cd/queue-service/pull/38) to store a queue. I implement a worker that takes that queue and requests the API.
Post what is received in the queue to the API
1. Receive json format string from queue.
```
'{"foo": "bar"}'
```
2. Post the json received in the queue to the API with the bearer token.
```
curl -X POST -H 'Authorization: Bearer dummy' -d '{"foo": "bar"}' ${apiUri}/v4/processHooks
```
https://github.com/screwdriver-cd/screwdriver/issues/1769#issuecomment-934107626
The `/v4/processHooks` API that we will create later response should return only 200, 201, 204. If we need another status code when we implement the API, we can adjust it!
https://github.com/screwdriver-cd/screwdriver/blob/master/plugins/webhooks/index.js
I confirm …

fix(1769): add sendWebhooks

---

lib/queue.js
plugins/helper.js
plugins/queue/scheduler.js
plugins/worker/lib/jobs.js
test/plugins/helper.test.js
test/plugins/queue/scheduler.test.js
test/plugins/worker/lib/jobs.test.js

We modified it in [last PR](https://github.com/screwdriver-cd/queue-service/pull/39) to send a queued webhook to API. But its [token](https://github.com/screwdriver-cd/queue-service/pull/39/files#diff-86652e44de215913f4ec263e133b40855eafdc5cc5c1c773a4cd56918a424b63R284-R287) is `undefined`.
- Generate a token before store webhook in a queue, and store webhook and generated token in queue. (ref. [here](https://github.com/screwdriver-cd/queue-service/blob/master/plugins/queue/scheduler.js#L707))
- Move retry callbacks for API from [ExecutorQueue](https://github.com/screwdriver-cd/queue-service/blob/9e873c2a57ea1e8a007b6c9c1fc53f579c88e7c2/lib/queue.js#L61-L74) to [helper](https://github.com/screwdriver-cd/queue-service/blob/master/plugins/helper.js).
- Fix tests, eslint. …

fix(1769): token is undefined when send webhook

---

plugins/helper.js
plugins/worker/lib/jobs.js
test/plugins/helper.test.js
test/plugins/worker/lib/jobs.test.js

If the scm response is slow, API requests to `/v4/processHooks` may take a long time and time out. In that case, the request will be retry and the event will be created twice.
- Fix so that it does not retry when there is a possibility request to `/v4/processHooks` is received. 
- Modify the response when access to `/v4/processHooks` times out.
https://github.com/screwdriver-cd/screwdriver/issues/2666
[got/retry](https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md)

[2] fix(2666): Do not retry when processHooks times out

---

plugins/worker/lib/jobs.js

The short-name value in the AWS region map was incorrect as per the region names
This PR fixes the value for key `northeast`

fix: region map value name

---

package.json
plugins/queue/scheduler.js
plugins/worker/lib/BlockedBy.js
test/plugins/queue/scheduler.test.js
test/plugins/worker/lib/BlockedBy.test.js

allowing user to override blocking behavior of builds from same job
when specified, build from same job will no longer block each other with a default wait time of 5 minute.
builds will trigger sequentially base on wait time and order of waiting queue
https://github.com/screwdriver-cd/screwdriver/issues/1712

feat(1712): Relaxing blockedBy for same job

---

package.json

This pull request was created by [mR4smussen](https://github.com/mR4smussen) using the JSFIX tool (https://jsfix.live) by Coana.tech (https://coana.tech).
It upgrades uuid to version 8.0.0.
The JSFIX tool used advanced program analysis to determine how uuid is used by screwdriver-queue-service and how it is affected by breaking changes in uuid version 8.0.0 (see details below). JSFIX checked for the 2 breaking changes affecting uuid version 8.0.0 and found 0 occurrences in screwdriver-queue-service. 
<strong>Install the [JSFIX GitHub app](https://github.com/apps/jsfix-updater) to receive other package updates from JSFIX.</strong>
***
<h3>Breaking change details</h3>
<details>
<summary><strong> 🚧 - Files JSFIX failed to analyze (carefully check that no source files are in this list before …

[JSFIX] Major version upgrade of uuid from version N/A to 8.0.0

---

package.json

`Laabr` contains vulnerable `lodash` and is detected by security tools. However, it is not used anywhere.
We remove `laabr` from `package.json`.
https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032

fix: Remove laabr

---

config/redis.js
lib/queue.js
plugins/helper.js
plugins/queue/scheduler.js
test/plugins/helper.test.js
test/plugins/queue/scheduler.test.js

When a job is archived in API, the the job data in redis (`periodicBuildConfigs`) is also synchronized.
But synchronization may fail due to communication errors with redis.
Then the deleted (archived) job will continue to run periodically and create events which is `No jobs to start`.
This PR changes `queue-service` to get job and pipeline data from API just before start periodic build.
Thus `periodicBuildConfigs` table will be no longer needed, we can remove this table.
Issues
- https://github.com/screwdriver-cd/screwdriver/issues/2743

fix(2743): get job and pipeline data from API just before start periodic build

---

plugins/worker/worker.js

queue-service fails to start when using [WORKER_MAX_TASK_PROCESSORS](https://github.com/screwdriver-cd/queue-service/blob/2a6d06aefa3cef9f4c16457c79024bb64e28a084/config/custom-environment-variables.yaml#L257).
```
{"level":"error","message":"Unhandled error: RangeError [ERR_OUT_OF_RANGE]: The value of \"n\" is out of range. It must be a non-negative number. Received '1050'\n    at EventEmitter.setMaxListeners (events.js:200:11)\n    at new MultiWorker (/usr/src/app/node_modules/node-resque/dist/core/multiWorker.js:20:38)\n    at Object.<anonymous> (/usr/src/app/node_modules/screwdriver-queue-service/plugins/worker/worker.js:42:21)\n    at Module._compile (internal/modules/cjs/loader.js:999:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at …
```

fix: queue-service can't start when WORKER_MAX_TASK_PROCESSORS is set

---

plugins/queue/scheduler.js

Sometimes scheduler is enqueuing same job multiple time which causes a periodic job to execute twice. 
Add delayedqueue & queue lock to prevent same job from getting enqueued twice.
Previous PR https://github.com/screwdriver-cd/queue-service/pull/65 added joblock, however logs suggests same job was picked at different times even with the fix.
https://github.com/screwdriver-cd/screwdriver/issues/2311
https://github.com/screwdriver-cd/queue-service/pull/65

Add queue locks in addition to job lock

---

plugins/queue/scheduler.js
plugins/queue/utils/cron.js
test/plugins/queue/scheduler.test.js
test/plugins/queue/utils/cron.test.js
test/plugins/worker/worker.test.js

Currently periodic build sometimes stops working. This is because it is failing to queue the next periodic job.
Periodic jobs may run earlier than scheduled. In this case, the next job will be scheduled at the time when the previous job was scheduled. If this happens, the next job is removed by `JobLock`.
The scheduled time of the next job is calculated based not on the current time but on a time slightly later than the current time. Then, even if a job is executed a little earlier, the next job is executed at the next timing.
https://github.com/screwdriver-cd/screwdriver/issues/2897
https://github.com/harrisiirak/cron-parser#readme
https://www.npmjs.com/package/node-resque
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMinutes
I confirm that this …

fix(2897): Fix periodic build scheduling

---

Dockerfile

queue-service server cannot receive `SIGTERM`
See this issue for details:
https://github.com/screwdriver-cd/screwdriver/issues/3062
- Fix Dockerfile as belows:
- Add tini process
- Run the service by `node ./bin/server` directly, not via `npm start`
Issue: https://github.com/screwdriver-cd/screwdriver/issues/3062
Docker and Node.js Best Practices: 
https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals

fix(3062): fix Dockerfile not to use npm start

---

Dockerfile
Dockerfile.local

In [the previous PR](https://github.com/screwdriver-cd/queue-service/pull/71), we have fixed the Dockerfile to use `tini`  to handle sigterm appropriately for graceful shutdown. However it seems there are some issues for signal TRAP with `tini` as [this comment](https://github.com/screwdriver-cd/screwdriver/pull/3063#issuecomment-2025390989) mentioned.
It switches `tini` to `dumb-init` for the init process in the container as same as `launcher` does.
[issue](https://github.com/screwdriver-cd/screwdriver/issues/3062)
[original comment](https://github.com/screwdriver-cd/screwdriver/pull/3063#issuecomment-2025390989)
[dumb-init official](https://github.com/Yelp/dumb-init)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's …

fix(3062): use dumb-init instead of tini

---

config/custom-environment-variables.yaml
config/default.yaml
package.json
test/data/executorConfig.json

Reverts screwdriver-cd/queue-service#74
We are still seeing some use cases of `k8s-vm` so we cannot really remove this dependency right now.

Revert "fix(3055): remove k8s-vm dependence"

---

plugins/queue/scheduler.js
test/plugins/queue/scheduler.test.js

https://github.com/screwdriver-cd/screwdriver/issues/3027
A job can be marked as virtual by adding the annotation `screwdriver.cd/virtualJob: true`. Such jobs should not be executed.
Builds added to the queue for virtual jobs should skip the execution.
Status of builds of such jobs should be updated to "SUCCESS".
https://github.com/screwdriver-cd/screwdriver/issues/3209

feat(3209): Skip execution of virtual job and mark it as SUCCESS

---

package.json
plugins/queue/scheduler.js
test/plugins/queue/scheduler.test.js

All the build status message are currently treated/visualized as warning in the UI. We need a mechanism to distinguish the messages based on severity.
Status message that is being set while skipping execution of virtual job should visualized as a information.
Set status message type to `INFO`.
https://github.com/screwdriver-cd/screwdriver/issues/3211

feat(3211): Set build status message type while skipping execution of virtual job

---

bin/server
config/custom-environment-variables.yaml
config/default.yaml
lib/server.js
plugins/queue/index.js
plugins/queue/put.js
test/lib/server.test.js
test/plugins/queue/index.test.js
test/plugins/queue/stats.test.js

Queue message POST route does not have payload validation control and defaults to hapi default value of 1MB
This PR makes the payload validation configurable

feat: add payload size validation to queue POST route
